### ISSUE TITLE
dummy app is not a fresh rails-new app

### ISSUE THREAD

**Issue by silva96** [michelson/rails-ui#3]
I can see you took some other app from somewhere else and pasted it in the test/dummy folder.

For example:

```
database: <%= ENV.fetch('POSTGRES_DATABASE', 'chaskiq-prod-local') %>
```

I guess we should delete the dummy app and create a new one 

```
rails new dummy -a propshaft -j esbuild --database sqlite3 --skip-test --css tailwind
```

**Comment by michelson** [comment]
It is generated by Rails New. I changed the database.yml at some point, as Heroku requires pg. We probably just need to change the config. In any case, we are not using active records at all.
